version: '3'
services:
  db:
    image: mysql
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3006:3006"
  demo-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=production
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  mysql_data: {}
  app-storage: {}
