default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "root"
  host: mysql # docker - mysql, local - localhost

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test